// lib/db/schema.ts
//
// Drizzle schema, generated by `drizzle-kit pull` against the live local
// Postgres and hand-fixed below. DDL lives in supabase/migrations/*.sql —
// do NOT run `drizzle-kit generate` or `drizzle-kit push`. Re-pull when
// the SQL schema changes and re-apply the hand-fixes:
//
//   1. Views use `.existing()` so Drizzle never tries to own/regenerate
//      their DDL (it would drop the `security_invoker=true` setting which
//      is security-critical — without it, the view runs as its owner
//      `raahuldutta`/postgres and silently bypasses RLS).
//   2. View array columns: drizzle-kit doesn't infer array types from view
//      projections. Apply `.array()` to: route, languages, help_categories,
//      flight_numbers, traveller_age_bands on public_trips; languages on
//      public_profiles.
//   3. `pending_notifications.payload` is typed via `$type<PendingNotificationPayload>`
//      to preserve the contract used by lib/notifications/{enqueue,dispatch}.ts.
//
// RLS policies are declared here only as documentation (drizzle-kit emits
// them as `pgPolicy(...)` during pull). They're inert at query time; the
// real policies live in the SQL migrations and are enforced by Postgres.

import {
  pgTable,
  index,
  foreignKey,
  pgPolicy,
  check,
  uuid,
  text,
  date,
  integer,
  timestamp,
  unique,
  boolean,
  jsonb,
  primaryKey,
  uniqueIndex,
  pgView,
  numeric,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import type { PendingNotificationPayload } from '@/types/db';

// ---------------------------------------------------------------------------
// Tables
// ---------------------------------------------------------------------------

export const trips = pgTable(
  'trips',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    userId: text('user_id').notNull(),
    kind: text({ enum: ['request', 'offer'] as const }).notNull(),
    route: text().array().notNull(),
    travelDate: date('travel_date').notNull(),
    flightNumbers: text('flight_numbers').array(),
    airline: text(),
    languages: text().array().default(['']).notNull(),
    genderPreference: text('gender_preference', {
      enum: ['any', 'male', 'female'] as const,
    }).default('any'),
    helpCategories: text('help_categories').array().default(['']).notNull(),
    thankYouEur: integer('thank_you_eur'),
    notes: text(),
    status: text({ enum: ['open', 'matched', 'completed', 'cancelled'] as const })
      .default('open')
      .notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('trips_date_idx').using('btree', table.travelDate.asc().nullsLast().op('date_ops')),
    index('trips_dest_idx').using('btree', sql`(route[array_length(route, 1)])`),
    index('trips_flight_numbers_gin').using(
      'gin',
      table.flightNumbers.asc().nullsLast().op('array_ops'),
    ),
    index('trips_kind_status_idx').using(
      'btree',
      table.kind.asc().nullsLast().op('text_ops'),
      table.status.asc().nullsLast().op('text_ops'),
    ),
    index('trips_languages_gin').using('gin', table.languages.asc().nullsLast().op('array_ops')),
    index('trips_origin_idx').using('btree', sql`(route[1])`),
    index('trips_status_idx').using('btree', table.status.asc().nullsLast().op('text_ops')),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [profiles.id],
      name: 'trips_user_id_fkey',
    }).onDelete('cascade'),
    pgPolicy('trips: match participants read full row', {
      as: 'permissive',
      for: 'select',
      to: ['public'],
    }),
    pgPolicy('trips: owner writes', { as: 'permissive', for: 'all', to: ['public'] }),
    pgPolicy('trips: public read', { as: 'permissive', for: 'select', to: ['public'] }),
    check('trips_kind_check', sql`kind = ANY (ARRAY['request'::text, 'offer'::text])`),
    check('trips_route_check', sql`array_length(route, 1) >= 2`),
    check(
      'trips_gender_preference_check',
      sql`gender_preference = ANY (ARRAY['any'::text, 'male'::text, 'female'::text])`,
    ),
    check('trips_thank_you_eur_check', sql`(thank_you_eur IS NULL) OR (thank_you_eur >= 0)`),
    check(
      'trips_status_check',
      sql`status = ANY (ARRAY['open'::text, 'matched'::text, 'completed'::text, 'cancelled'::text])`,
    ),
  ],
);

export const matchRequests = pgTable(
  'match_requests',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    tripId: uuid('trip_id').notNull(),
    requesterId: text('requester_id').notNull(),
    introMessage: text('intro_message'),
    status: text({ enum: ['pending', 'accepted', 'declined', 'auto_declined'] as const })
      .default('pending')
      .notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    respondedAt: timestamp('responded_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    index('match_requests_requester_idx').using(
      'btree',
      table.requesterId.asc().nullsLast().op('text_ops'),
    ),
    index('match_requests_status_idx').using(
      'btree',
      table.status.asc().nullsLast().op('text_ops'),
    ),
    index('match_requests_trip_idx').using('btree', table.tripId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.requesterId],
      foreignColumns: [profiles.id],
      name: 'match_requests_requester_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.tripId],
      foreignColumns: [trips.id],
      name: 'match_requests_trip_id_fkey',
    }).onDelete('cascade'),
    unique('match_requests_trip_id_requester_id_key').on(table.tripId, table.requesterId),
  ],
);

export const matches = pgTable(
  'matches',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    matchRequestId: uuid('match_request_id').notNull(),
    tripId: uuid('trip_id').notNull(),
    posterId: text('poster_id').notNull(),
    requesterId: text('requester_id').notNull(),
    status: text({ enum: ['active', 'completed', 'cancelled', 'disputed'] as const })
      .default('active')
      .notNull(),
    posterMarkedComplete: boolean('poster_marked_complete').default(false).notNull(),
    requesterMarkedComplete: boolean('requester_marked_complete').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    completedAt: timestamp('completed_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    index('matches_poster_idx').using('btree', table.posterId.asc().nullsLast().op('text_ops')),
    index('matches_requester_idx').using(
      'btree',
      table.requesterId.asc().nullsLast().op('text_ops'),
    ),
    index('matches_trip_idx').using('btree', table.tripId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.matchRequestId],
      foreignColumns: [matchRequests.id],
      name: 'matches_match_request_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.tripId],
      foreignColumns: [trips.id],
      name: 'matches_trip_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.posterId],
      foreignColumns: [profiles.id],
      name: 'matches_poster_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.requesterId],
      foreignColumns: [profiles.id],
      name: 'matches_requester_id_fkey',
    }).onDelete('cascade'),
    unique('matches_match_request_id_key').on(table.matchRequestId),
  ],
);

export const messages = pgTable(
  'messages',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    matchId: uuid('match_id').notNull(),
    senderId: text('sender_id').notNull(),
    body: text().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('messages_match_idx').using(
      'btree',
      table.matchId.asc().nullsLast().op('timestamptz_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    foreignKey({
      columns: [table.matchId],
      foreignColumns: [matches.id],
      name: 'messages_match_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.senderId],
      foreignColumns: [profiles.id],
      name: 'messages_sender_id_fkey',
    }).onDelete('cascade'),
    check('messages_body_check', sql`(length(body) >= 1) AND (length(body) <= 4000)`),
  ],
);

export const reviews = pgTable(
  'reviews',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    matchId: uuid('match_id').notNull(),
    reviewerId: text('reviewer_id').notNull(),
    revieweeId: text('reviewee_id').notNull(),
    rating: integer().notNull(),
    body: text(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('reviews_reviewee_idx').using('btree', table.revieweeId.asc().nullsLast().op('text_ops')),
    foreignKey({
      columns: [table.matchId],
      foreignColumns: [matches.id],
      name: 'reviews_match_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.reviewerId],
      foreignColumns: [profiles.id],
      name: 'reviews_reviewer_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.revieweeId],
      foreignColumns: [profiles.id],
      name: 'reviews_reviewee_id_fkey',
    }).onDelete('cascade'),
    unique('reviews_match_id_reviewer_id_key').on(table.matchId, table.reviewerId),
    check('reviews_rating_check', sql`(rating >= 1) AND (rating <= 5)`),
  ],
);

export const tripPhotos = pgTable(
  'trip_photos',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    matchId: uuid('match_id').notNull(),
    uploaderId: text('uploader_id').notNull(),
    photoUrl: text('photo_url').notNull(),
    caption: text(),
    visibility: text({ enum: ['private', 'profile', 'public'] as const })
      .default('private')
      .notNull(),
    otherPartyConsented: boolean('other_party_consented').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('trip_photos_match_idx').using('btree', table.matchId.asc().nullsLast().op('uuid_ops')),
    index('trip_photos_visibility_idx').using(
      'btree',
      table.visibility.asc().nullsLast().op('text_ops'),
    ),
    foreignKey({
      columns: [table.matchId],
      foreignColumns: [matches.id],
      name: 'trip_photos_match_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.uploaderId],
      foreignColumns: [profiles.id],
      name: 'trip_photos_uploader_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const reports = pgTable(
  'reports',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    reporterId: text('reporter_id').notNull(),
    subjectId: text('subject_id').notNull(),
    reason: text().notNull(),
    context: jsonb(),
    status: text({ enum: ['open', 'reviewing', 'actioned', 'dismissed'] as const })
      .default('open')
      .notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.reporterId],
      foreignColumns: [profiles.id],
      name: 'reports_reporter_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.subjectId],
      foreignColumns: [profiles.id],
      name: 'reports_subject_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const flightCache = pgTable('flight_cache', {
  flightIata: text('flight_iata').primaryKey().notNull(),
  airlineIata: text('airline_iata'),
  airlineName: text('airline_name'),
  depIata: text('dep_iata').notNull(),
  depAirport: text('dep_airport'),
  depTimezone: text('dep_timezone'),
  arrIata: text('arr_iata').notNull(),
  arrAirport: text('arr_airport'),
  arrTimezone: text('arr_timezone'),
  durationMinutes: integer('duration_minutes'),
  cachedAt: timestamp('cached_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const profiles = pgTable(
  'profiles',
  {
    id: text().primaryKey().notNull(),
    role: text({ enum: ['family', 'companion'] as const }).notNull(),
    displayName: text('display_name'),
    photoUrl: text('photo_url'),
    bio: text(),
    email: text(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    whatsappNumber: text('whatsapp_number'),
    linkedinUrl: text('linkedin_url'),
    facebookUrl: text('facebook_url'),
    twitterUrl: text('twitter_url'),
    instagramUrl: text('instagram_url'),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    isActive: boolean('is_active').default(true).notNull(),
    whatsappValidatedAt: timestamp('whatsapp_validated_at', { withTimezone: true, mode: 'string' }),
    whatsappOtpHash: text('whatsapp_otp_hash'),
    whatsappOtpExpiresAt: timestamp('whatsapp_otp_expires_at', {
      withTimezone: true,
      mode: 'string',
    }),
    lastNotifiedAt: timestamp('last_notified_at', { withTimezone: true, mode: 'string' }),
    onboardingComplete: boolean('onboarding_complete').default(false).notNull(),
  },
  (table) => [
    index('profiles_onboarding_complete_idx').using(
      'btree',
      table.onboardingComplete.asc().nullsLast().op('bool_ops'),
    ),
    index('profiles_role_idx').using('btree', table.role.asc().nullsLast().op('text_ops')),
  ],
);

export const pendingNotifications = pgTable(
  'pending_notifications',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    newTripId: uuid('new_trip_id').notNull(),
    recipientUserId: text('recipient_user_id').notNull(),
    channel: text({ enum: ['email', 'whatsapp'] as const }).notNull(),
    payload: jsonb().$type<PendingNotificationPayload>().notNull(),
    status: text({ enum: ['pending', 'in_flight', 'sent', 'failed', 'skipped'] as const })
      .default('pending')
      .notNull(),
    attempts: integer().default(0).notNull(),
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    lastError: text('last_error'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    sentAt: timestamp('sent_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    index('pending_notifications_pickup_idx')
      .using('btree', table.nextAttemptAt.asc().nullsLast().op('timestamptz_ops'))
      .where(sql`(status = 'pending'::text)`),
    index('pending_notifications_recipient_idx').using(
      'btree',
      table.recipientUserId.asc().nullsLast().op('text_ops'),
      table.status.asc().nullsLast().op('text_ops'),
    ),
    index('pending_notifications_trip_idx').using(
      'btree',
      table.newTripId.asc().nullsLast().op('uuid_ops'),
    ),
    foreignKey({
      columns: [table.newTripId],
      foreignColumns: [trips.id],
      name: 'pending_notifications_new_trip_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.recipientUserId],
      foreignColumns: [profiles.id],
      name: 'pending_notifications_recipient_user_id_fkey',
    }).onDelete('cascade'),
    unique('pending_notifications_new_trip_id_recipient_user_id_channel_key').on(
      table.newTripId,
      table.recipientUserId,
      table.channel,
    ),
  ],
);

export const tripTravellers = pgTable(
  'trip_travellers',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    tripId: uuid('trip_id').notNull(),
    firstName: text('first_name'),
    ageBand: text('age_band', { enum: ['60-70', '70-80', '80+'] as const }),
    medicalNotes: text('medical_notes'),
    sortOrder: integer('sort_order').default(0).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('trip_travellers_sort_idx').using(
      'btree',
      table.tripId.asc().nullsLast().op('int4_ops'),
      table.sortOrder.asc().nullsLast().op('int4_ops'),
    ),
    index('trip_travellers_trip_id_idx').using(
      'btree',
      table.tripId.asc().nullsLast().op('uuid_ops'),
    ),
    foreignKey({
      columns: [table.tripId],
      foreignColumns: [trips.id],
      name: 'trip_elders_trip_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const tripLegs = pgTable(
  'trip_legs',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    tripId: uuid('trip_id').notNull(),
    legIndex: integer('leg_index').notNull(),
    origin: text().notNull(),
    destination: text().notNull(),
    travelDate: date('travel_date').notNull(),
    flightNumber: text('flight_number'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('trip_legs_flight_date_idx')
      .using(
        'btree',
        table.flightNumber.asc().nullsLast().op('text_ops'),
        table.travelDate.asc().nullsLast().op('text_ops'),
      )
      .where(sql`(flight_number IS NOT NULL)`),
    index('trip_legs_od_date_idx').using(
      'btree',
      table.origin.asc().nullsLast().op('text_ops'),
      table.destination.asc().nullsLast().op('date_ops'),
      table.travelDate.asc().nullsLast().op('date_ops'),
    ),
    index('trip_legs_trip_idx').using('btree', table.tripId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.tripId],
      foreignColumns: [trips.id],
      name: 'trip_legs_trip_id_fkey',
    }).onDelete('cascade'),
    unique('trip_legs_trip_id_leg_index_key').on(table.tripId, table.legIndex),
  ],
);

export const blocks = pgTable(
  'blocks',
  {
    blockerId: text('blocker_id').notNull(),
    blockedId: text('blocked_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.blockerId],
      foreignColumns: [profiles.id],
      name: 'blocks_blocker_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.blockedId],
      foreignColumns: [profiles.id],
      name: 'blocks_blocked_id_fkey',
    }).onDelete('cascade'),
    primaryKey({ columns: [table.blockerId, table.blockedId], name: 'blocks_pkey' }),
    check('blocks_check', sql`blocker_id <> blocked_id`),
  ],
);

export const profileLanguages = pgTable(
  'profile_languages',
  {
    profileId: text('profile_id').notNull(),
    language: text().notNull(),
    isPrimary: boolean('is_primary').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('profile_languages_language_idx').using(
      'btree',
      table.language.asc().nullsLast().op('text_ops'),
    ),
    uniqueIndex('profile_languages_one_primary_per_user')
      .using('btree', table.profileId.asc().nullsLast().op('text_ops'))
      .where(sql`is_primary`),
    foreignKey({
      columns: [table.profileId],
      foreignColumns: [profiles.id],
      name: 'profile_languages_profile_id_fkey',
    }).onDelete('cascade'),
    primaryKey({ columns: [table.profileId, table.language], name: 'profile_languages_pkey' }),
  ],
);

export const rateLimits = pgTable(
  'rate_limits',
  {
    userId: text('user_id').notNull(),
    endpoint: text().notNull(),
    minuteBucket: timestamp('minute_bucket', { withTimezone: true, mode: 'string' }).notNull(),
    count: integer().default(0).notNull(),
  },
  (table) => [
    index('rate_limits_bucket_idx').using(
      'btree',
      table.minuteBucket.asc().nullsLast().op('timestamptz_ops'),
    ),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [profiles.id],
      name: 'rate_limits_user_id_fkey',
    }).onDelete('cascade'),
    primaryKey({
      columns: [table.userId, table.endpoint, table.minuteBucket],
      name: 'rate_limits_pkey',
    }),
  ],
);

// ---------------------------------------------------------------------------
// Views — DDL lives in supabase/migrations/*.sql. `.existing()` makes
// Drizzle treat these as managed-elsewhere (typing only). Array columns
// fixed by hand because drizzle-kit pull emits view projections as scalars.
// ---------------------------------------------------------------------------

export const profileReviewStats = pgView('profile_review_stats', {
  userId: text('user_id'),
  reviewCount: integer('review_count'),
  averageRating: numeric('average_rating'),
}).existing();

export const publicProfiles = pgView('public_profiles', {
  id: text(),
  role: text({ enum: ['family', 'companion'] as const }),
  displayName: text('display_name'),
  photoUrl: text('photo_url'),
  bio: text(),
  languages: text().array(),
  primaryLanguage: text('primary_language'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }),
  isActive: boolean('is_active'),
  linkedinUrl: text('linkedin_url'),
  facebookUrl: text('facebook_url'),
  twitterUrl: text('twitter_url'),
  instagramUrl: text('instagram_url'),
}).existing();

export const publicTrips = pgView('public_trips', {
  id: uuid(),
  userId: text('user_id'),
  kind: text({ enum: ['request', 'offer'] as const }),
  route: text().array(),
  travelDate: date('travel_date'),
  airline: text(),
  languages: text().array(),
  genderPreference: text('gender_preference', { enum: ['any', 'male', 'female'] as const }),
  helpCategories: text('help_categories').array(),
  thankYouEur: integer('thank_you_eur'),
  status: text({ enum: ['open', 'matched', 'completed', 'cancelled'] as const }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }),
  flightNumbers: text('flight_numbers').array(),
  travellerAgeBands: text('traveller_age_bands').array(),
  travellerCount: integer('traveller_count'),
}).existing();
