import { ImageResponse } from 'next/og';

/**
 * Apple touch icon — shown on iOS home screens when someone adds Saathi.
 * 180×180 is the size iOS prefers; smaller variants are auto-generated by
 * the OS. Renders the 🌼 mark on a cream ground matching the landing page.
 */
export const size = { width: 180, height: 180 };
export const contentType = 'image/png';

export default function AppleIcon() {
  return new ImageResponse(
    <div
      style={{
        width: '100%',
        height: '100%',
        background: '#faf9f7',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 130,
      }}
    >
      🌼
    </div>,
    { ...size, emoji: 'twemoji' },
  );
}
