import type { MetadataRoute } from 'next';
import { siteUrl } from '@/lib/site';

/**
 * /robots.txt — auto-generated by Next at build time. Allow everything by
 * default; the only off-limits paths are private app surfaces (auth,
 * dashboard, post wizards, etc.) where indexing would dump signed-in-only
 * pages into search results.
 *
 * Add new private prefixes here as the app grows. Public marketing pages
 * (/, /about, /faq, /search, /trip/*, /profile/*) stay open.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/auth/',
          '/dashboard',
          '/onboarding',
          '/post/',
          '/match/',
          // Sentry tunnel route — no need for crawlers to poke this.
          '/monitoring',
        ],
      },
    ],
    sitemap: `${siteUrl()}/sitemap.xml`,
    host: siteUrl(),
  };
}
