/** Languages offered in the post wizard. Curated, not exhaustive. */
export const LANGUAGES: readonly string[] = [
  'English',
  'Bengali',
  'Hindi',
  'Urdu',
  'Punjabi',
  'Tamil',
  'Telugu',
  'Marathi',
  'Gujarati',
  'Malayalam',
  'Kannada',
  'Mandarin',
  'Cantonese',
  'Tagalog',
  'Vietnamese',
  'Indonesian',
  'Japanese',
  'Korean',
  'Arabic',
  'Turkish',
  'Persian',
  'Swahili',
  'Yoruba',
  'Igbo',
  'French',
  'German',
  'Dutch',
  'Spanish',
  'Portuguese',
  'Italian',
  'Polish',
  'Russian',
  'Ukrainian',
  'Romanian',
  'Greek',
];

export const HELP_CATEGORIES: readonly { key: string; label: string; description: string }[] = [
  {
    key: 'wheelchair',
    label: 'Wheelchair assistance',
    description: 'Pushing, transfers, gate-to-gate',
  },
  { key: 'bags', label: 'Carrying bags', description: 'Lifting, trolley handling' },
  { key: 'immigration', label: 'Immigration forms', description: 'Reading, filling, explaining' },
  { key: 'food', label: 'Meals and dietary', description: 'Vegetarian, Jain, diabetic, halal' },
  { key: 'prayer', label: 'Prayer time & facilities', description: 'Finding a quiet space' },
  { key: 'medication', label: 'Medication reminders', description: 'Timing, dosage' },
  { key: 'language', label: 'Language translation', description: 'At counters and security' },
  { key: 'wayfinding', label: 'Wayfinding', description: 'Gates, transfers, signage' },
];
